apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadgenerator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: hhttps://github.com/laxmanraju4144/GitOps.git
    targetRevision: main
    path: base/loadgenerator
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
